// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVPqKdmNilhBEnh8tKKQF_a_XtZjfm9uU',
    appId: '1:41416187582:web:db07e179ce8d6a86d8c8ef',
    messagingSenderId: '41416187582',
    projectId: 'ankigpt-prod',
    authDomain: 'ankigpt-prod.firebaseapp.com',
    storageBucket: 'ankigpt-prod.appspot.com',
    measurementId: 'G-M6JJKD0LQZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPo9ODXd3wpHHMTDjq5wUzt8AHYEUkh0I',
    appId: '1:41416187582:ios:58ffeb0113809e94d8c8ef',
    messagingSenderId: '41416187582',
    projectId: 'ankigpt-prod',
    storageBucket: 'ankigpt-prod.appspot.com',
    iosClientId:
        '41416187582-iqsb70pqjabt0d92bbelqi9q80p2jov2.apps.googleusercontent.com',
    iosBundleId: 'de.ankigpt.ankigpt',
  );
}
