// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDRiD1Bg3CFKNxBV-WbFzAzG7NwryuAGA',
    appId: '1:531541464051:web:d60054f53262319f29f886',
    messagingSenderId: '531541464051',
    projectId: 'ankigpt-dev',
    authDomain: 'ankigpt-dev.firebaseapp.com',
    storageBucket: 'ankigpt-dev.appspot.com',
    measurementId: 'G-V05MKN7P4S',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATb60gTXbbIVJrax3L4B1nTGIu5FtoGqU',
    appId: '1:531541464051:ios:806a57abca8f91b729f886',
    messagingSenderId: '531541464051',
    projectId: 'ankigpt-dev',
    storageBucket: 'ankigpt-dev.appspot.com',
    iosClientId: '531541464051-vbpstmiu4m4undrcprs8e190lk0da7jp.apps.googleusercontent.com',
    iosBundleId: 'wtf.ankigpt.app',
  );
}
